/* 영작 마스터 — 단원과 문장
   교재 목차 순서(2장~13장)를 따르고, 문장은 새로 쓴 연습용 문장이에요.
   한 줄 형식:  "한국어 = English | 다른 정답 | 다른 정답"
   한국어 정답이 여러 개면 " ; " 로 구분해요.  예) "그는 키가 크다 ; 그는 키가 커 = He is tall."
*/
window.LEVELS = [
  { id: "l1", name: "왕초급" },
  { id: "l2", name: "초급" },
  { id: "l3", name: "중급" },
  { id: "l4", name: "고수" },
  { id: "l5", name: "마스터" }
];

window.UNITS = [
/* ───────── 왕초급 · 2장 인칭대명사와 be동사 ───────── */
{ id: "c2a", level: "l1", ch: "2장", name: "be동사 현재·과거", short: "be동사",
  tip: "주어에 따라 am / are / is, 과거는 was / were를 써요.",
  items: [
"나는 학생이다. = I am a student. | I'm a student.",
"그녀는 내 누나이다. ; 그녀는 내 언니이다. ; 그녀는 내 여동생이다. = She is my sister. | She's my sister.",
"우리는 같은 반이다. = We are in the same class. | We're in the same class.",
"그들은 나의 친구들이다. = They are my friends. | They're my friends.",
"너는 키가 크다. = You are tall. | You're tall.",
"그는 지금 집에 있다. = He is at home now. | He's at home now. | He is home now.",
"그 고양이는 귀엽다. = The cat is cute.",
"이 책은 재미있다. = This book is interesting. | This book is fun.",
"나는 어제 피곤했다. = I was tired yesterday.",
"그들은 작년에 초등학생이었다. = They were elementary school students last year.",
"그 영화는 정말 좋았다. = The movie was really good. | The movie was very good.",
"우리는 그때 공원에 있었다. = We were in the park then. | We were at the park then.",
"날씨가 어제 추웠다. = The weather was cold yesterday. | It was cold yesterday.",
"내 방은 깨끗하다. = My room is clean.",
"너희들은 오늘 매우 바쁘다. = You are very busy today. | You're very busy today.",
"그 시험은 쉬웠다. = The test was easy. | The exam was easy.",
"나의 아빠는 요리사이다. = My dad is a cook. | My father is a cook. | My dad is a chef. | My father is a chef.",
"그 상자들은 무거웠다. = The boxes were heavy.",
"민수는 지난주에 아팠다. = Minsu was sick last week. | Minsu was ill last week.",
"나는 지금 행복하다. = I am happy now. | I'm happy now."
]},
{ id: "c2b", level: "l1", ch: "2장", name: "be동사 부정문·의문문", short: "be 부정·의문",
  tip: "부정은 be동사 뒤에 not, 의문은 be동사를 주어 앞으로 보내요.",
  items: [
"나는 배고프지 않다. = I am not hungry. | I'm not hungry.",
"그는 의사가 아니다. = He is not a doctor. | He isn't a doctor. | He's not a doctor.",
"우리는 늦지 않았다. = We were not late. | We weren't late.",
"그 가방은 내 것이 아니다. = The bag is not mine. | The bag isn't mine.",
"그들은 교실에 없었다. = They were not in the classroom. | They weren't in the classroom.",
"그 질문은 어렵지 않았다. = The question was not difficult. | The question wasn't difficult. | The question was not hard. | The question wasn't hard.",
"너는 혼자가 아니다. = You are not alone. | You aren't alone. | You're not alone.",
"그녀는 어제 학교에 없었다. = She was not at school yesterday. | She wasn't at school yesterday.",
"너는 학생이니? = Are you a student?",
"그는 너의 형이니? ; 그는 너의 오빠니? = Is he your brother?",
"그들은 친절했니? = Were they kind?",
"그 영화는 무서웠니? = Was the movie scary?",
"너의 엄마는 집에 계시니? = Is your mom at home? | Is your mother at home? | Is your mom home? | Is your mother home?",
"너는 어제 아팠니? = Were you sick yesterday? | Were you ill yesterday?",
"이것은 너의 연필이니? = Is this your pencil?",
"그 가게는 오늘 문을 열었니? = Is the store open today? | Is the shop open today?",
"우리는 지각이니? = Are we late?",
"그 시험은 어려웠니? = Was the test difficult? | Was the test hard? | Was the exam difficult? | Was the exam hard?",
"그 아이들은 공원에 있니? = Are the children in the park? | Are the kids in the park?",
"나는 틀리지 않았다. = I was not wrong. | I wasn't wrong."
]},
{ id: "c2c", level: "l1", ch: "2장", name: "There is/are · 대명사의 격", short: "There is·격",
  tip: "'~이 있다'는 There is(단수) / There are(복수). 소유격 my, 목적격 me, 소유대명사 mine을 구별해요.",
  items: [
"책상 위에 책이 한 권 있다. = There is a book on the desk. | There's a book on the desk.",
"공원에 아이들이 많이 있다. = There are many children in the park. | There are a lot of children in the park. | There are many kids in the park. | There are a lot of kids in the park.",
"냉장고에 우유가 조금 있다. = There is some milk in the fridge. | There's some milk in the fridge. | There is some milk in the refrigerator.",
"우리 반에는 학생이 스무 명 있다. = There are twenty students in my class. | There are twenty students in our class. | There are 20 students in my class. | There are 20 students in our class.",
"방에 아무도 없었다. = There was nobody in the room. | There was no one in the room. | There wasn't anybody in the room. | There wasn't anyone in the room.",
"벽에 사진이 두 장 있었다. = There were two pictures on the wall. | There were two photos on the wall.",
"근처에 은행이 있니? = Is there a bank near here? | Is there a bank nearby?",
"이것은 나의 자전거이다. = This is my bike. | This is my bicycle.",
"그 자전거는 나의 것이다. = The bike is mine. | The bicycle is mine.",
"그녀는 나를 안다. = She knows me.",
"나는 그를 좋아한다. = I like him.",
"그들의 집은 크다. = Their house is big. | Their house is large.",
"그 빨간 우산은 그녀의 것이다. = The red umbrella is hers.",
"우리 선생님은 우리를 도와주신다. = Our teacher helps us.",
"그것의 꼬리는 길다. = Its tail is long.",
"이 공책은 너의 것이니? = Is this notebook yours?",
"나는 그들을 매일 본다. = I see them every day.",
"그의 이름은 준호이다. = His name is Junho.",
"그 선택은 우리의 것이다. = The choice is ours.",
"너의 신발은 새것이다. = Your shoes are new."
]},
/* ───────── 왕초급 · 3장 일반동사 ───────── */
{ id: "c3a", level: "l1", ch: "3장", name: "일반동사 현재형", short: "현재형",
  tip: "주어가 3인칭 단수(he, she, it…)면 동사에 -s / -es를 붙여요.",
  items: [
"나는 매일 아침을 먹는다. = I eat breakfast every day. | I have breakfast every day.",
"우리는 학교에 걸어간다. = We walk to school.",
"그는 축구를 좋아한다. = He likes soccer.",
"그녀는 수학을 공부한다. = She studies math.",
"내 동생은 TV를 본다. = My brother watches TV. | My sister watches TV.",
"그들은 주말마다 영화를 본다. = They watch movies every weekend. | They watch a movie every weekend.",
"우리 엄마는 은행에서 일하신다. = My mom works at a bank. | My mother works at a bank.",
"그 버스는 8시에 떠난다. = The bus leaves at eight. | The bus leaves at 8. | The bus leaves at eight o'clock.",
"민지는 피아노를 매우 잘 친다. = Minji plays the piano very well.",
"나의 아빠는 매일 신문을 읽으신다. = My dad reads the newspaper every day. | My father reads the newspaper every day. | My dad reads a newspaper every day.",
"그는 숙제를 저녁에 한다. = He does his homework in the evening.",
"그 가게는 10시에 문을 닫는다. = The store closes at ten. | The store closes at 10. | The shop closes at ten. | The shop closes at 10.",
"나는 버스로 학교에 간다. = I go to school by bus.",
"그녀는 안경을 쓴다. = She wears glasses.",
"고양이들은 생선을 좋아한다. = Cats like fish.",
"그는 머리를 아침에 감는다. = He washes his hair in the morning.",
"나의 할머니는 시골에 사신다. = My grandmother lives in the country. | My grandma lives in the country. | My grandmother lives in the countryside. | My grandma lives in the countryside.",
"그 아기는 많이 운다. = The baby cries a lot.",
"우리는 일요일마다 교회에 간다. = We go to church every Sunday. | We go to church on Sundays.",
"그는 영어를 잘한다. = He speaks English well. | He is good at English."
]},
{ id: "c3b", level: "l1", ch: "3장", name: "일반동사 과거형", short: "과거형",
  tip: "규칙 동사는 -ed, 불규칙 동사(go→went, eat→ate…)는 따로 외워요.",
  items: [
"나는 어제 축구를 했다. = I played soccer yesterday.",
"그녀는 지난주에 할머니를 방문했다. = She visited her grandmother last week. | She visited her grandma last week.",
"우리는 영화를 보고 울었다. = We watched the movie and cried.",
"그는 오늘 아침에 늦게 일어났다. = He got up late this morning. | He woke up late this morning.",
"나는 어제 도서관에 갔다. = I went to the library yesterday.",
"그들은 점심으로 피자를 먹었다. = They ate pizza for lunch. | They had pizza for lunch.",
"민호는 새 신발을 샀다. = Minho bought new shoes.",
"우리는 해변에서 사진을 찍었다. = We took pictures at the beach. | We took photos at the beach.",
"그녀는 나에게 편지를 썼다. = She wrote me a letter. | She wrote a letter to me.",
"나는 그 소식을 들었다. = I heard the news.",
"그는 지갑을 잃어버렸다. = He lost his wallet.",
"우리는 작년에 부산으로 이사했다. = We moved to Busan last year.",
"나는 숙제를 끝냈다. = I finished my homework.",
"그녀는 공원에서 친구를 만났다. = She met her friend in the park. | She met a friend in the park.",
"그들은 노래를 부르고 춤을 췄다. = They sang and danced.",
"나는 어젯밤에 일찍 잤다. = I went to bed early last night. | I slept early last night.",
"그는 문을 열었다. = He opened the door.",
"우리 팀이 그 경기에서 이겼다. = Our team won the game. | My team won the game. | Our team won the match.",
"나는 그 책을 두 번 읽었다. = I read the book twice.",
"그녀는 버스에 우산을 두고 왔다. = She left her umbrella on the bus."
]},
{ id: "c3c", level: "l1", ch: "3장", name: "일반동사 부정문·의문문", short: "부정·의문",
  tip: "don't / doesn't / didn't + 동사원형, 의문은 Do / Does / Did로 시작해요.",
  items: [
"나는 커피를 마시지 않는다. = I don't drink coffee. | I do not drink coffee.",
"그는 고기를 먹지 않는다. = He doesn't eat meat. | He does not eat meat.",
"우리는 그 답을 알지 못했다. = We didn't know the answer. | We did not know the answer.",
"그녀는 어제 학교에 오지 않았다. = She didn't come to school yesterday. | She did not come to school yesterday.",
"내 동생은 채소를 좋아하지 않는다. = My brother doesn't like vegetables. | My sister doesn't like vegetables. | My brother does not like vegetables. | My sister does not like vegetables.",
"그들은 일요일에 일하지 않는다. = They don't work on Sundays. | They do not work on Sundays. | They don't work on Sunday.",
"나는 그 영화를 보지 않았다. = I didn't watch the movie. | I did not watch the movie. | I didn't see the movie. | I did not see the movie.",
"그 버스는 여기에 서지 않는다. = The bus doesn't stop here. | The bus does not stop here.",
"너는 개를 좋아하니? = Do you like dogs?",
"그는 피아노를 치니? = Does he play the piano?",
"너는 어제 그를 만났니? = Did you meet him yesterday? | Did you see him yesterday?",
"그녀는 서울에 사니? = Does she live in Seoul?",
"그들은 그 경기를 이겼니? = Did they win the game? | Did they win the match?",
"너의 아빠는 매일 운동하시니? = Does your dad exercise every day? | Does your father exercise every day?",
"너는 숙제를 했니? = Did you do your homework?",
"그 가게는 빵을 파니? = Does the store sell bread? | Does the shop sell bread?",
"너희는 같은 학교에 다니니? = Do you go to the same school?",
"나는 오늘 아침을 먹지 않았다. = I didn't eat breakfast this morning. | I did not eat breakfast this morning. | I didn't have breakfast this morning. | I did not have breakfast this morning.",
"그녀는 그 질문에 대답하지 않았다. = She didn't answer the question. | She did not answer the question.",
"그 기차는 제시간에 도착했니? = Did the train arrive on time?"
]},
/* ───────── 초급 · 4장 명사와 관사 ───────── */
{ id: "c4a", level: "l2", ch: "4장", name: "셀 수 있는 명사", short: "셀 수 있는 명사",
  tip: "둘 이상이면 복수형: -s, -es, y→ies, f→ves, 불규칙(child→children, man→men…)",
  items: [
"나는 사과 세 개가 있다. = I have three apples.",
"그녀는 상자 두 개를 들고 있다. = She is carrying two boxes. | She is holding two boxes.",
"나무에 나뭇잎이 많다. = There are many leaves on the tree. | The tree has many leaves. | There are a lot of leaves on the tree.",
"그 도시에는 교회가 많다. = There are many churches in the city. | The city has many churches. | There are a lot of churches in the city.",
"아이들이 운동장에서 놀고 있다. = The children are playing on the playground. | Children are playing on the playground. | The kids are playing on the playground.",
"나는 매일 이를 닦는다. = I brush my teeth every day.",
"그 남자들은 소방관이다. = The men are firefighters.",
"농장에 양이 열 마리 있다. = There are ten sheep on the farm. | There are 10 sheep on the farm.",
"그 여자들은 간호사이다. = The women are nurses.",
"나는 매일 발을 씻는다. = I wash my feet every day.",
"그녀는 아기가 둘 있다. = She has two babies.",
"우리는 동물원에서 늑대 두 마리를 보았다. = We saw two wolves at the zoo.",
"그 쥐들은 작다. = The mice are small.",
"선반 위에 칼이 세 개 있다. = There are three knives on the shelf.",
"그는 감자 다섯 개를 샀다. = He bought five potatoes.",
"나는 도시 세 곳을 방문했다. = I visited three cities.",
"그 공원에는 벤치가 많다. = There are many benches in the park. | The park has many benches. | There are a lot of benches in the park.",
"그 소년들은 장난감을 좋아한다. = The boys like toys.",
"나는 사진을 많이 찍었다. = I took many photos. | I took a lot of photos. | I took many pictures. | I took a lot of pictures.",
"사람들이 줄을 서 있다. = People are standing in line."
]},
{ id: "c4b", level: "l2", ch: "4장", name: "셀 수 없는 명사·수량", short: "셀 수 없는 명사",
  tip: "물, 빵, 돈 같은 명사는 a/an, -s를 못 붙여요. a glass of, a piece of로 세요.",
  items: [
"나는 물 한 잔을 마셨다. = I drank a glass of water.",
"그녀는 매일 아침 우유 한 잔을 마신다. = She drinks a glass of milk every morning.",
"나는 빵 두 조각을 먹었다. = I ate two pieces of bread. | I ate two slices of bread.",
"케이크 한 조각 줄래? = Can I have a piece of cake? | Can you give me a piece of cake? | Could I have a piece of cake?",
"그는 커피 두 잔을 주문했다. = He ordered two cups of coffee.",
"나는 종이 한 장이 필요하다. = I need a piece of paper. | I need a sheet of paper.",
"우리는 시간이 많지 않다. = We don't have much time. | We do not have much time.",
"그는 돈이 조금 있다. = He has some money. | He has a little money.",
"병에 물이 조금 있다. = There is a little water in the bottle. | There is some water in the bottle.",
"그녀는 나에게 좋은 조언을 해 주었다. = She gave me good advice. | She gave me some good advice. | She gave me a piece of good advice.",
"나는 설탕 두 숟가락을 넣었다. = I put in two spoonfuls of sugar. | I added two spoonfuls of sugar. | I put two spoons of sugar in it.",
"우리는 주스 세 병을 샀다. = We bought three bottles of juice.",
"그 가방에는 정보가 많다. = The bag has a lot of information. | There is a lot of information in the bag.",
"행복은 돈으로 살 수 없다. = Money can't buy happiness. | You can't buy happiness with money. | Money cannot buy happiness.",
"그는 서울에 산다. = He lives in Seoul.",
"나는 수프 한 그릇을 먹었다. = I had a bowl of soup. | I ate a bowl of soup.",
"그녀는 치즈 한 조각을 샀다. = She bought a piece of cheese. | She bought a slice of cheese.",
"교실에 가구가 많지 않다. = There isn't much furniture in the classroom. | There is not much furniture in the classroom.",
"밖에 눈이 많이 있다. = There is a lot of snow outside. | There's a lot of snow outside.",
"나는 매일 차 두 잔을 마신다. = I drink two cups of tea every day."
]},
{ id: "c4c", level: "l2", ch: "4장", name: "관사 a/an · the", short: "관사",
  tip: "처음 말할 때 a/an, 이미 아는 것·하나뿐인 것은 the. 식사·운동·by 교통수단 앞에는 관사 없이!",
  items: [
"나는 개 한 마리가 있다. = I have a dog.",
"그녀는 우산이 하나 필요하다. = She needs an umbrella.",
"그는 한 시간 동안 기다렸다. = He waited for an hour.",
"나는 사과 하나와 오렌지 하나를 샀다. = I bought an apple and an orange.",
"나는 고양이를 봤다. 그 고양이는 검은색이었다. = I saw a cat. The cat was black.",
"창문 좀 열어 줄래? = Can you open the window? | Could you open the window?",
"태양은 동쪽에서 뜬다. = The sun rises in the east.",
"그녀는 바이올린을 켠다. = She plays the violin.",
"달이 매우 밝다. = The moon is very bright.",
"우리는 일주일에 두 번 수영한다. = We swim twice a week.",
"나는 7시에 아침을 먹는다. = I have breakfast at seven. | I eat breakfast at seven. | I have breakfast at 7. | I eat breakfast at 7.",
"그는 방과 후에 농구를 한다. = He plays basketball after school.",
"우리는 지하철로 학교에 간다. = We go to school by subway.",
"그녀는 하루에 세 번 이를 닦는다. = She brushes her teeth three times a day.",
"그 남자는 정직한 사람이다. = The man is an honest man. | The man is an honest person.",
"나는 그 영화의 끝을 좋아했다. = I liked the end of the movie. | I liked the ending of the movie.",
"그는 대학생이다. = He is a university student. | He is a college student.",
"하늘이 파랗다. = The sky is blue.",
"나는 저녁 식사 후에 산책을 한다. = I take a walk after dinner.",
"그녀는 택시를 타고 집에 갔다. = She went home by taxi. | She took a taxi home."
]},
/* ───────── 초급 · 5장 대명사 ───────── */
{ id: "c5a", level: "l2", ch: "5장", name: "지시대명사·one·some/any", short: "지시·one·some",
  tip: "this/that(단수), these/those(복수). 같은 종류 하나는 one, 긍정문 some / 부정·의문문 any.",
  items: [
"이것은 나의 가방이다. = This is my bag.",
"저것들은 그의 신발이다. = Those are his shoes.",
"이 사람들은 나의 사촌들이다. = These are my cousins.",
"저 남자는 우리 선생님이다. = That man is our teacher.",
"이 꽃들은 아름답다. = These flowers are beautiful.",
"저것은 너의 공이니? = Is that your ball?",
"나는 펜을 잃어버렸다. 하나 사야 한다. = I lost my pen. I need to buy one. | I lost my pen. I have to buy one.",
"이 셔츠는 너무 작다. 더 큰 것이 있나요? = This shirt is too small. Do you have a bigger one?",
"나는 빨간 것보다 파란 것이 더 좋다. = I like the blue one better than the red one. | I like the blue one more than the red one.",
"나는 우유를 좀 원한다. = I want some milk.",
"그녀는 친구가 좀 있다. = She has some friends.",
"나는 돈이 하나도 없다. = I don't have any money. | I do not have any money. | I have no money.",
"질문이 있나요? = Do you have any questions?",
"케이크 좀 드실래요? = Would you like some cake?",
"냉장고에 주스가 하나도 없다. = There isn't any juice in the fridge. | There is no juice in the fridge. | There is not any juice in the fridge.",
"그는 형제가 하나도 없다. = He doesn't have any brothers. | He does not have any brothers. | He has no brothers.",
"이 컵은 더럽다. 깨끗한 것을 줄래? = This cup is dirty. Can you give me a clean one? | This cup is dirty. Could you give me a clean one?",
"저 집들은 오래되었다. = Those houses are old.",
"나는 사과를 좀 샀다. = I bought some apples.",
"방에 누가 있니? = Is there anyone in the room? | Is there anybody in the room?"
]},
{ id: "c5b", level: "l2", ch: "5장", name: "비인칭 it · 재귀대명사", short: "it·재귀대명사",
  tip: "날씨·시간·날짜·거리를 말할 때 주어 it(해석 안 함). '자기 자신'은 myself, himself, themselves…",
  items: [
"비가 오고 있다. = It is raining. | It's raining.",
"오늘은 춥다. = It is cold today. | It's cold today.",
"지금 3시이다. = It is three o'clock now. | It's three o'clock now. | It is 3 o'clock now. | It's 3 now. | It is three now.",
"오늘은 월요일이다. = It is Monday today. | It's Monday today. | Today is Monday.",
"밖이 어둡다. = It is dark outside. | It's dark outside.",
"역까지 2킬로미터이다. = It is two kilometers to the station. | It's two kilometers to the station. | It is 2 kilometers to the station.",
"오늘은 내 생일이다. = It is my birthday today. | It's my birthday today. | Today is my birthday.",
"몇 시니? = What time is it?",
"여름에는 덥다. = It is hot in summer. | It's hot in summer. | It is hot in the summer.",
"나는 거울 속의 나 자신을 보았다. = I looked at myself in the mirror. | I saw myself in the mirror.",
"그는 요리하다가 다쳤다. = He hurt himself while cooking. | He hurt himself while he was cooking.",
"그녀는 자신을 사랑한다. = She loves herself.",
"마음껏 드세요. = Help yourself. | Help yourselves.",
"그들은 파티에서 즐거운 시간을 보냈다. = They enjoyed themselves at the party. | They had a good time at the party.",
"나는 그것을 직접 만들었다. = I made it myself.",
"너 자신을 믿어라. = Believe in yourself.",
"우리는 우리 자신을 소개했다. = We introduced ourselves.",
"그 아이는 혼자서 옷을 입었다. = The child dressed himself. | The child dressed herself. | The kid dressed himself.",
"그는 혼자서 그 문제를 풀었다. = He solved the problem himself. | He solved the problem by himself.",
"고양이가 스스로 몸을 씻고 있다. = The cat is washing itself. | The cat is cleaning itself."
]},
/* ───────── 초급 · 6장 시제 ───────── */
{ id: "c6a", level: "l2", ch: "6장", name: "현재시제·과거시제", short: "현재·과거",
  tip: "습관·사실은 현재, 끝난 일은 과거. yesterday, last ~, ago가 나오면 과거예요.",
  items: [
"물은 100도에서 끓는다. = Water boils at 100 degrees. | Water boils at one hundred degrees.",
"지구는 태양 주위를 돈다. = The earth goes around the sun. | The Earth moves around the sun. | The earth moves around the sun.",
"나는 보통 7시에 일어난다. = I usually get up at seven. | I usually wake up at seven. | I usually get up at 7. | I usually wake up at 7.",
"그는 매주 토요일에 테니스를 친다. = He plays tennis every Saturday. | He plays tennis on Saturdays.",
"나는 3년 전에 그녀를 만났다. = I met her three years ago.",
"한국 전쟁은 1950년에 일어났다. = The Korean War broke out in 1950. | The Korean War started in 1950.",
"우리는 지난 여름에 제주도에 갔다. = We went to Jeju Island last summer. | We went to Jeju last summer.",
"그녀는 어제 머리를 잘랐다. = She got a haircut yesterday. | She cut her hair yesterday. | She had her hair cut yesterday.",
"우리 학교는 8시 반에 시작한다. = Our school starts at eight thirty. | My school starts at 8:30. | Our school starts at 8:30. | My school starts at eight thirty.",
"나는 어제 그 책을 다 읽었다. = I finished reading the book yesterday. | I finished the book yesterday.",
"그는 매일 학교에 자전거를 타고 간다. = He rides his bike to school every day. | He goes to school by bike every day. | He rides a bike to school every day.",
"그들은 두 시간 전에 떠났다. = They left two hours ago.",
"나의 형은 대학에서 공부한다. = My brother studies at university. | My brother studies at college.",
"나는 지난밤에 이상한 꿈을 꾸었다. = I had a strange dream last night.",
"해는 서쪽으로 진다. = The sun sets in the west.",
"우리 가족은 저녁을 함께 먹는다. = My family eats dinner together. | My family has dinner together. | Our family has dinner together. | Our family eats dinner together.",
"그녀는 2010년에 태어났다. = She was born in 2010.",
"나는 어제 많이 웃었다. = I laughed a lot yesterday.",
"그는 아침마다 조깅을 한다. = He jogs every morning. | He goes jogging every morning.",
"우리는 지난주에 시험을 봤다. = We took a test last week. | We had a test last week. | We took an exam last week."
]},
{ id: "c6b", level: "l2", ch: "6장", name: "현재진행형·과거진행형", short: "진행형",
  tip: "be동사 + 동사-ing. 지금 하는 중이면 am/are/is, 그때 하는 중이었으면 was/were.",
  items: [
"나는 지금 숙제를 하고 있다. = I am doing my homework now. | I'm doing my homework now.",
"그녀는 음악을 듣고 있다. = She is listening to music. | She's listening to music.",
"아이들이 수영장에서 수영하고 있다. = The children are swimming in the pool. | The kids are swimming in the pool.",
"그는 버스를 기다리고 있다. = He is waiting for the bus. | He's waiting for the bus. | He is waiting for a bus.",
"우리는 저녁을 먹고 있다. = We are having dinner. | We're having dinner. | We are eating dinner.",
"밖에 눈이 오고 있다. = It is snowing outside. | It's snowing outside.",
"그 아기는 자고 있다. = The baby is sleeping.",
"그들은 축구를 하고 있다. = They are playing soccer. | They're playing soccer.",
"아빠는 차를 세차하고 계신다. = Dad is washing the car. | My dad is washing the car. | My father is washing the car.",
"그녀는 편지를 쓰고 있다. = She is writing a letter.",
"나는 그때 TV를 보고 있었다. = I was watching TV then. | I was watching TV at that time.",
"그는 어젯밤 10시에 공부하고 있었다. = He was studying at ten last night. | He was studying at 10 last night.",
"우리는 공원에서 걷고 있었다. = We were walking in the park.",
"그녀는 전화로 이야기하고 있었다. = She was talking on the phone.",
"비가 하루 종일 오고 있었다. = It was raining all day.",
"그들은 노래를 부르고 있었다. = They were singing a song. | They were singing.",
"엄마는 부엌에서 요리하고 계셨다. = Mom was cooking in the kitchen. | My mom was cooking in the kitchen. | My mother was cooking in the kitchen.",
"나는 친구를 기다리고 있었다. = I was waiting for my friend. | I was waiting for a friend.",
"그 남자는 달리고 있었다. = The man was running.",
"학생들이 시험을 보고 있다. = The students are taking a test. | The students are taking an exam."
]},
{ id: "c6c", level: "l2", ch: "6장", name: "진행형 부정문·의문문", short: "진행 부정·의문",
  tip: "부정: be동사 + not + -ing, 의문: Be동사 + 주어 + -ing ~?",
  items: [
"나는 지금 자고 있지 않다. = I am not sleeping now. | I'm not sleeping now.",
"그는 TV를 보고 있지 않다. = He is not watching TV. | He isn't watching TV. | He's not watching TV.",
"우리는 놀고 있지 않다. 공부하고 있다. = We are not playing. We are studying. | We aren't playing. We're studying. | We're not playing. We're studying.",
"그녀는 그때 울고 있지 않았다. = She was not crying then. | She wasn't crying then. | She wasn't crying at that time.",
"그들은 내 말을 듣고 있지 않았다. = They were not listening to me. | They weren't listening to me.",
"비가 오고 있지 않다. = It is not raining. | It isn't raining. | It's not raining.",
"아이들은 자고 있지 않았다. = The children were not sleeping. | The children weren't sleeping. | The kids weren't sleeping.",
"나는 너를 비웃고 있지 않다. = I am not laughing at you. | I'm not laughing at you.",
"너는 무엇을 하고 있니? = What are you doing?",
"그는 지금 공부하고 있니? = Is he studying now?",
"그들은 축구를 하고 있니? = Are they playing soccer?",
"너는 그때 자고 있었니? = Were you sleeping then? | Were you sleeping at that time?",
"그녀는 무엇을 읽고 있니? = What is she reading?",
"밖에 비가 오고 있니? = Is it raining outside?",
"너는 나를 기다리고 있었니? = Were you waiting for me?",
"그는 어디에 가고 있니? = Where is he going?",
"너의 엄마는 요리하고 계시니? = Is your mom cooking? | Is your mother cooking?",
"그들은 왜 웃고 있었니? = Why were they laughing?",
"누가 피아노를 치고 있니? = Who is playing the piano?",
"그 개는 짖고 있지 않았다. = The dog was not barking. | The dog wasn't barking."
]},
/* ───────── 중급 · 7장 조동사 ───────── */
{ id: "c7a", level: "l3", ch: "7장", name: "will · be going to", short: "will·going to",
  tip: "미래: will + 동사원형(즉석 결정·예측), be going to + 동사원형(미리 정한 계획).",
  items: [
"나는 내일 너에게 전화할게. = I will call you tomorrow. | I'll call you tomorrow.",
"내일은 비가 올 것이다. = It will rain tomorrow. | It'll rain tomorrow. | It is going to rain tomorrow.",
"그는 다음 달에 열네 살이 될 것이다. = He will be fourteen next month. | He'll be fourteen next month. | He will be 14 next month.",
"나는 그 비밀을 말하지 않을 것이다. = I will not tell the secret. | I won't tell the secret. | I won't tell anyone the secret.",
"너는 파티에 올 거니? = Will you come to the party? | Are you going to come to the party?",
"내가 문을 열어 줄게. = I will open the door for you. | I'll open the door for you. | I will open the door. | I'll open the door.",
"우리는 이번 주말에 캠핑을 갈 것이다. = We are going to go camping this weekend. | We're going to go camping this weekend. | We will go camping this weekend.",
"그녀는 내년에 유학을 갈 예정이다. = She is going to study abroad next year. | She's going to study abroad next year.",
"나는 오늘 밤에 영화를 볼 것이다. = I am going to watch a movie tonight. | I'm going to watch a movie tonight. | I will watch a movie tonight.",
"그들은 새 집을 살 예정이다. = They are going to buy a new house. | They're going to buy a new house.",
"너는 방학 동안 무엇을 할 거니? = What are you going to do during the vacation? | What will you do during the vacation? | What are you going to do during vacation?",
"나는 그를 다시 만나지 않을 것이다. = I am not going to meet him again. | I'm not going to meet him again. | I won't meet him again. | I will not meet him again. | I won't see him again.",
"조심해! 넘어지겠어. = Be careful! You are going to fall. | Be careful! You're going to fall. | Watch out! You're going to fall.",
"그는 곧 도착할 것이다. = He will arrive soon. | He'll arrive soon. | He will be here soon.",
"나는 열심히 공부할 거야. = I will study hard. | I'll study hard. | I am going to study hard.",
"그 가게는 내일 문을 열지 않을 것이다. = The store will not open tomorrow. | The store won't open tomorrow. | The shop won't open tomorrow.",
"너는 그녀를 도와줄 거니? = Will you help her? | Are you going to help her?",
"우리 형은 다음 주에 군대에 갈 것이다. = My brother is going to join the army next week. | My brother will join the army next week.",
"나는 저녁으로 스파게티를 만들 거야. = I am going to make spaghetti for dinner. | I'm going to make spaghetti for dinner. | I will make spaghetti for dinner.",
"그 경기는 7시에 시작할 것이다. = The game will start at seven. | The game will start at 7. | The game is going to start at seven."
]},
{ id: "c7b", level: "l3", ch: "7장", name: "can · be able to · may", short: "can·may",
  tip: "can = ~할 수 있다(능력)·~해도 된다(허락) = be able to. may = ~해도 된다·~일지도 모른다.",
  items: [
"나는 수영을 할 수 있다. = I can swim. | I am able to swim.",
"그녀는 중국어를 말할 수 있다. = She can speak Chinese. | She is able to speak Chinese.",
"그는 그 상자를 들 수 없다. = He can't lift the box. | He cannot lift the box. | He isn't able to lift the box.",
"너는 자전거를 탈 수 있니? = Can you ride a bike? | Can you ride a bicycle?",
"내 펜을 써도 된다. = You can use my pen. | You may use my pen.",
"창문을 열어도 될까요? = Can I open the window? | May I open the window?",
"나는 어제 잠을 잘 수 없었다. = I couldn't sleep yesterday. | I could not sleep yesterday. | I wasn't able to sleep yesterday.",
"그녀는 다섯 살 때 읽을 수 있었다. = She could read when she was five. | She was able to read when she was five.",
"너는 곧 걸을 수 있을 것이다. = You will be able to walk soon.",
"나는 그 시험에 통과할 수 있었다. = I was able to pass the test. | I was able to pass the exam.",
"우리는 그 문제를 풀 수 없었다. = We couldn't solve the problem. | We could not solve the problem. | We weren't able to solve the problem.",
"들어가도 될까요? = May I come in? | Can I come in?",
"너는 지금 집에 가도 된다. = You may go home now. | You can go home now.",
"그는 오늘 늦을지도 모른다. = He may be late today. | He might be late today.",
"그것은 사실이 아닐지도 모른다. = It may not be true. | It might not be true.",
"내일 눈이 올지도 모른다. = It may snow tomorrow. | It might snow tomorrow.",
"그녀는 집에 있을지도 모른다. = She may be at home. | She might be at home. | She may be home.",
"여기서 사진을 찍으면 안 된다. = You may not take pictures here. | You can't take pictures here. | You cannot take pictures here. | You may not take photos here.",
"도와드릴까요? = May I help you? | Can I help you?",
"나는 그 노래를 기억할 수 없다. = I can't remember the song. | I cannot remember the song."
]},
{ id: "c7c", level: "l3", ch: "7장", name: "must · have to · should", short: "must·should",
  tip: "must / have to = ~해야 한다, should = ~하는 게 좋다. don't have to = ~할 필요 없다, must not = ~하면 안 된다.",
  items: [
"너는 안전벨트를 매야 한다. = You must wear a seat belt. | You have to wear a seat belt. | You must fasten your seat belt.",
"우리는 규칙을 지켜야 한다. = We must follow the rules. | We have to follow the rules. | We must keep the rules.",
"너는 여기서 뛰면 안 된다. = You must not run here. | You mustn't run here.",
"그는 오늘 숙제를 끝내야 한다. = He has to finish his homework today. | He must finish his homework today.",
"나는 일찍 일어나야 했다. = I had to get up early. | I had to wake up early.",
"너는 서두를 필요가 없다. = You don't have to hurry. | You do not have to hurry. | You don't need to hurry.",
"그녀는 교복을 입을 필요가 없다. = She doesn't have to wear a school uniform. | She does not have to wear a school uniform.",
"우리는 내일 학교에 가야 하니? = Do we have to go to school tomorrow?",
"그는 피곤한 게 틀림없다. = He must be tired.",
"그녀는 부자인 것이 틀림없다. = She must be rich.",
"너는 채소를 더 먹어야 한다. = You should eat more vegetables.",
"너는 부모님 말씀을 들어야 한다. = You should listen to your parents.",
"우리는 물을 낭비하면 안 된다. = We should not waste water. | We shouldn't waste water. | We must not waste water.",
"너는 의사에게 가 보는 게 좋겠다. = You should see a doctor. | You should go to see a doctor.",
"나는 무엇을 해야 하니? = What should I do?",
"너는 수업 시간에 떠들면 안 된다. = You must not talk in class. | You shouldn't talk in class. | You should not talk in class. | You mustn't talk in class.",
"그는 안경을 써야 한다. = He has to wear glasses. | He must wear glasses.",
"우리는 그를 기다릴 필요가 없었다. = We didn't have to wait for him. | We did not have to wait for him.",
"너는 일찍 자는 게 좋겠다. = You should go to bed early. | You should sleep early.",
"그들은 다음 주에 이사해야 한다. = They have to move next week. | They must move next week."
]},
/* ───────── 중급 · 8장 형용사, 부사, 비교 ───────── */
{ id: "c8a", level: "l3", ch: "8장", name: "형용사·수량 형용사", short: "형용사",
  tip: "형용사는 명사 앞이나 be동사 뒤. many/few(셀 수 있는), much/little(셀 수 없는), a lot of는 둘 다!",
  items: [
"그녀는 친절한 선생님이다. = She is a kind teacher.",
"그 이야기는 슬프다. = The story is sad.",
"나는 새 휴대폰이 있다. = I have a new phone. | I have a new cell phone.",
"그 산은 매우 높다. = The mountain is very high. | The mountain is very tall.",
"그는 빨간 모자를 쓰고 있다. = He is wearing a red cap. | He is wearing a red hat.",
"나는 뭔가 차가운 것을 원한다. = I want something cold.",
"그녀는 친구가 많다. = She has many friends. | She has a lot of friends. | She has lots of friends.",
"나는 돈이 많지 않다. = I don't have much money. | I do not have much money.",
"그는 실수를 거의 하지 않는다. = He makes few mistakes.",
"나는 친구가 몇 명 있다. = I have a few friends.",
"병에 물이 거의 없다. = There is little water in the bottle.",
"나는 시간이 조금 있다. = I have a little time.",
"그 도시에는 사람이 많다. = There are many people in the city. | There are a lot of people in the city.",
"우리는 숙제가 많다. = We have a lot of homework. | We have lots of homework. | We have much homework.",
"그 방은 따뜻하고 조용하다. = The room is warm and quiet.",
"이 수프는 너무 뜨겁다. = This soup is too hot.",
"그 시험에 통과한 학생은 거의 없었다. = Few students passed the test. | Few students passed the exam.",
"나는 특별한 무언가를 하고 싶다. = I want to do something special.",
"그녀의 머리카락은 길고 검다. = Her hair is long and black.",
"그것은 쉬운 질문이었다. = It was an easy question."
]},
{ id: "c8b", level: "l3", ch: "8장", name: "부사·빈도부사", short: "부사",
  tip: "부사는 동사·형용사를 꾸며요(대개 형용사+ly). always, usually, often, sometimes, never는 일반동사 앞, be동사 뒤!",
  items: [
"그는 천천히 걷는다. = He walks slowly.",
"그녀는 노래를 아름답게 부른다. = She sings beautifully.",
"그 시험은 정말 쉬웠다. = The test was really easy. | The exam was really easy.",
"나는 그 질문에 쉽게 대답했다. = I answered the question easily.",
"그는 매우 빨리 달린다. = He runs very fast.",
"그들은 열심히 일한다. = They work hard.",
"다행히도 아무도 다치지 않았다. = Luckily, nobody was hurt. | Fortunately, nobody was hurt. | Luckily, no one was hurt. | Fortunately, no one was hurt.",
"나는 어젯밤 늦게 잤다. = I went to bed late last night. | I slept late last night.",
"그녀는 조용히 문을 닫았다. = She closed the door quietly.",
"나는 항상 7시에 일어난다. = I always get up at seven. | I always wake up at seven. | I always get up at 7. | I always wake up at 7.",
"그는 보통 버스로 학교에 간다. = He usually goes to school by bus.",
"우리는 자주 영화를 보러 간다. = We often go to the movies.",
"나는 가끔 아침을 거른다. = I sometimes skip breakfast.",
"그녀는 절대 늦지 않는다. = She is never late.",
"그는 항상 친절하다. = He is always kind.",
"나는 결코 거짓말을 하지 않는다. = I never lie. | I never tell lies. | I never tell a lie.",
"그들은 종종 공원에서 논다. = They often play in the park.",
"나의 엄마는 보통 바쁘시다. = My mom is usually busy. | My mother is usually busy.",
"너는 얼마나 자주 운동하니? = How often do you exercise?",
"그는 거의 고기를 먹지 않는다. = He hardly eats meat. | He rarely eats meat. | He seldom eats meat."
]},
{ id: "c8c", level: "l3", ch: "8장", name: "원급·비교급·최상급", short: "비교",
  tip: "as 원급 as(~만큼), 비교급 + than(~보다 더), the 최상급 + in/of(~중 가장).",
  items: [
"나는 내 형만큼 키가 크다. = I am as tall as my brother. | I'm as tall as my brother.",
"이 가방은 저것만큼 무겁지 않다. = This bag is not as heavy as that one. | This bag isn't as heavy as that one.",
"그녀는 나만큼 빨리 달릴 수 있다. = She can run as fast as I can. | She can run as fast as me.",
"오늘은 어제보다 덥다. = Today is hotter than yesterday. | It is hotter today than yesterday. | It's hotter today than yesterday.",
"내 방은 너의 방보다 더 크다. = My room is bigger than yours. | My room is bigger than your room. | My room is larger than yours.",
"이 문제는 저 문제보다 더 어렵다. = This problem is more difficult than that one. | This question is more difficult than that one. | This problem is harder than that one.",
"그는 나보다 더 일찍 일어난다. = He gets up earlier than I do. | He gets up earlier than me. | He wakes up earlier than me.",
"건강이 돈보다 더 중요하다. = Health is more important than money.",
"그녀의 점수는 내 점수보다 더 좋았다. = Her score was better than mine.",
"기차가 버스보다 더 빠르다. = The train is faster than the bus. | A train is faster than a bus. | Trains are faster than buses.",
"그는 우리 반에서 가장 키가 크다. = He is the tallest in my class. | He is the tallest in our class. | He is the tallest student in my class.",
"이것은 세상에서 가장 긴 강이다. = This is the longest river in the world.",
"그녀는 셋 중에서 가장 어리다. = She is the youngest of the three.",
"그것은 내 인생 최고의 날이었다. = It was the best day of my life.",
"이것은 그 가게에서 가장 비싼 시계이다. = This is the most expensive watch in the store. | This is the most expensive watch in the shop.",
"겨울은 가장 추운 계절이다. = Winter is the coldest season.",
"그는 그 팀에서 가장 유명한 선수이다. = He is the most famous player on the team. | He is the most famous player in the team.",
"나의 할아버지는 우리 가족 중에서 가장 나이가 많으시다. = My grandfather is the oldest in my family. | My grandpa is the oldest in my family. | My grandfather is the oldest in our family.",
"수학이 나에게 가장 어려운 과목이다. = Math is the most difficult subject for me. | Math is the hardest subject for me.",
"이 영화가 저 영화보다 더 재미있다. = This movie is more interesting than that one. | This movie is more fun than that one."
]},
/* ───────── 중급 · 9장 의문문, 명령문, 감탄문 ───────── */
{ id: "c9a", level: "l3", ch: "9장", name: "의문사 의문문", short: "의문사",
  tip: "who(누구), what(무엇), which(어느 것), when(언제), where(어디), why(왜), how(어떻게)로 시작해요.",
  items: [
"너는 누구를 기다리고 있니? = Who are you waiting for?",
"누가 창문을 깼니? = Who broke the window?",
"너는 점심으로 무엇을 먹었니? = What did you eat for lunch? | What did you have for lunch?",
"너는 무슨 색을 좋아하니? = What color do you like?",
"너는 어느 것을 원하니, 빨간 것 아니면 파란 것? = Which do you want, the red one or the blue one?",
"너의 생일은 언제니? = When is your birthday?",
"너는 언제 숙제를 하니? = When do you do your homework?",
"화장실이 어디에 있니? = Where is the bathroom? | Where is the restroom?",
"너는 어디에서 그 가방을 샀니? = Where did you buy the bag?",
"너는 왜 늦었니? = Why were you late?",
"그녀는 왜 울고 있니? = Why is she crying?",
"너는 학교에 어떻게 가니? = How do you go to school? | How do you get to school?",
"날씨는 어떠니? = How is the weather? | What is the weather like? | What's the weather like?",
"너는 몇 살이니? = How old are you?",
"이 신발은 얼마니? = How much are these shoes?",
"너는 형제가 몇 명 있니? = How many brothers do you have?",
"너는 얼마나 자주 수영하니? = How often do you swim?",
"그 영화는 얼마나 길었니? = How long was the movie?",
"이것은 누구의 책이니? = Whose book is this?",
"너는 왜 그를 좋아하니? = Why do you like him?"
]},
{ id: "c9b", level: "l3", ch: "9장", name: "부가 의문문·부정 의문문", short: "부가·부정 의문",
  tip: "부가의문문: 긍정 → 부정 꼬리(isn't it?), 부정 → 긍정 꼬리(is it?). 부정의문문은 Isn't / Don't ~?",
  items: [
"날씨가 좋다, 그렇지 않니? = It is nice, isn't it? | It's nice, isn't it? | The weather is nice, isn't it?",
"너는 피곤하다, 그렇지 않니? = You are tired, aren't you? | You're tired, aren't you?",
"그는 축구를 좋아한다, 그렇지 않니? = He likes soccer, doesn't he?",
"그녀는 어제 왔다, 그렇지 않니? = She came yesterday, didn't she?",
"너는 수영할 수 있다, 그렇지 않니? = You can swim, can't you?",
"그들은 학생이 아니다, 그렇지? = They are not students, are they? | They aren't students, are they?",
"너는 고기를 먹지 않는다, 그렇지? = You don't eat meat, do you? | You do not eat meat, do you?",
"그는 늦지 않을 것이다, 그렇지? = He won't be late, will he? | He will not be late, will he?",
"그 시험은 어려웠다, 그렇지 않니? = The test was difficult, wasn't it? | The test was hard, wasn't it? | The exam was difficult, wasn't it?",
"문을 닫아라, 알았지? = Close the door, will you?",
"우리 같이 가자, 그럴래? = Let's go together, shall we?",
"너는 배고프지 않니? = Aren't you hungry?",
"그는 너의 형이 아니니? = Isn't he your brother?",
"너는 그녀를 모르니? = Don't you know her?",
"그녀는 커피를 마시지 않니? = Doesn't she drink coffee?",
"너는 그 영화를 보지 않았니? = Didn't you watch the movie? | Didn't you see the movie?",
"그것은 멋지지 않니? = Isn't it great? | Isn't it cool? | Isn't it wonderful?",
"너는 숙제를 끝내지 않았니? = Didn't you finish your homework?",
"그녀는 친절하다, 그렇지 않니? = She is kind, isn't she? | She's kind, isn't she?",
"너는 파티에 가지 않을 거니? = Aren't you going to the party? | Won't you go to the party? | Aren't you going to go to the party?"
]},
{ id: "c9c", level: "l3", ch: "9장", name: "명령문·감탄문", short: "명령·감탄",
  tip: "명령문은 동사원형으로 시작(부정은 Don't ~). 감탄문: What a 형용사 명사 (주어 동사)! / How 형용사 (주어 동사)!",
  items: [
"창문을 열어라. = Open the window.",
"조용히 해라. = Be quiet.",
"교실에서 뛰지 마라. = Don't run in the classroom. | Do not run in the classroom.",
"늦지 마라. = Don't be late. | Do not be late.",
"손을 깨끗이 씻어라. = Wash your hands. | Wash your hands clean.",
"친구들에게 친절하게 대해라. = Be kind to your friends.",
"함께 점심 먹자. = Let's have lunch together. | Let's eat lunch together.",
"공원에 가지 말자. = Let's not go to the park.",
"열심히 공부해라, 그러면 시험에 통과할 것이다. = Study hard, and you will pass the test. | Study hard, and you'll pass the test. | Study hard, and you will pass the exam.",
"서둘러라, 그렇지 않으면 버스를 놓칠 것이다. = Hurry up, or you will miss the bus. | Hurry up, or you'll miss the bus. | Hurry, or you will miss the bus.",
"그것을 만지지 마. = Don't touch it. | Do not touch it.",
"정말 아름다운 꽃이구나! = What a beautiful flower! | What a beautiful flower it is!",
"그는 정말 친절한 소년이구나! = What a kind boy he is!",
"정말 멋진 날이구나! = What a nice day! | What a nice day it is! | What a wonderful day! | What a beautiful day!",
"그 영화는 정말 재미있구나! = How interesting the movie is! | What an interesting movie!",
"정말 춥구나! = How cold it is! | It's so cold!",
"그녀는 정말 귀엽구나! = How cute she is!",
"그는 정말 빨리 달리는구나! = How fast he runs!",
"그것들은 정말 큰 개들이구나! = What big dogs they are! | What big dogs!",
"정말 맛있구나! = How delicious it is! | How delicious!"
]},
/* ───────── 고수 · 10장 문장의 형식 ───────── */
{ id: "c10a", level: "l4", ch: "10장", name: "1~3형식·감각동사", short: "1~3형식",
  tip: "감각동사(look, feel, sound, smell, taste) 뒤에는 형용사! look like + 명사.",
  items: [
"그 아기는 웃었다. = The baby smiled. | The baby laughed.",
"새들이 하늘을 난다. = Birds fly in the sky.",
"그는 배가 고파졌다. = He got hungry. | He became hungry.",
"그녀는 의사가 되었다. = She became a doctor.",
"너는 오늘 행복해 보인다. = You look happy today.",
"이 수프는 맛있다. ; 이 수프는 맛이 좋다. = This soup tastes good. | This soup tastes delicious.",
"그 계획은 좋게 들린다. ; 그거 좋은 생각 같다. = The plan sounds good. | That sounds good. | That sounds like a good plan.",
"이 꽃은 좋은 냄새가 난다. = This flower smells good. | This flower smells nice.",
"나는 피곤하다고 느꼈다. ; 나는 피곤했다. = I felt tired.",
"그 담요는 부드럽게 느껴진다. = The blanket feels soft.",
"그는 그의 아빠처럼 보인다. ; 그는 아빠를 닮았다. = He looks like his dad. | He looks like his father.",
"날씨가 따뜻해졌다. = The weather became warm. | The weather got warm. | It got warm.",
"나는 매일 일기를 쓴다. = I keep a diary every day. | I write in my diary every day.",
"그녀는 그 상자를 열었다. = She opened the box.",
"우리는 그 경기를 즐겼다. = We enjoyed the game.",
"그 소식은 이상하게 들린다. = The news sounds strange.",
"그 우유는 상한 냄새가 났다. = The milk smelled bad.",
"그는 조용히 있었다. = He stayed quiet. | He kept quiet. | He remained quiet.",
"그 케이크는 달콤한 맛이 난다. = The cake tastes sweet.",
"그것은 진짜 같아 보인다. = It looks real."
]},
{ id: "c10b", level: "l4", ch: "10장", name: "4형식 → 3형식", short: "4형식",
  tip: "주어 + 동사 + 사람 + 물건. 순서를 바꾸면 give/send/show/tell → to, buy/make/cook → for, ask → of.",
  items: [
"그는 나에게 선물을 주었다. = He gave me a present. | He gave a present to me. | He gave me a gift. | He gave a gift to me.",
"그녀는 우리에게 사진들을 보여 주었다. = She showed us the pictures. | She showed the pictures to us. | She showed us the photos.",
"나는 그에게 편지를 보냈다. = I sent him a letter. | I sent a letter to him.",
"선생님은 우리에게 재미있는 이야기를 해 주셨다. = The teacher told us a funny story. | The teacher told a funny story to us. | The teacher told us an interesting story.",
"그는 나에게 그의 공책을 빌려 주었다. = He lent me his notebook. | He lent his notebook to me.",
"나에게 소금 좀 건네줄래? = Can you pass me the salt? | Could you pass me the salt? | Can you pass the salt to me?",
"엄마는 나에게 새 신발을 사 주셨다. = Mom bought me new shoes. | My mom bought me new shoes. | My mom bought new shoes for me. | My mother bought me new shoes.",
"아빠는 우리에게 저녁을 만들어 주셨다. = Dad made us dinner. | My dad made us dinner. | My dad made dinner for us. | My father made dinner for us.",
"그녀는 나에게 케이크를 구워 주었다. = She baked me a cake. | She baked a cake for me.",
"그는 나에게 질문을 하나 했다. = He asked me a question. | He asked a question of me.",
"나는 그녀에게 꽃을 주었다. = I gave her flowers. | I gave flowers to her. | I gave her some flowers.",
"그는 학생들에게 영어를 가르친다. = He teaches students English. | He teaches English to students.",
"할머니는 나에게 스웨터를 만들어 주셨다. = My grandmother made me a sweater. | My grandma made me a sweater. | My grandmother made a sweater for me.",
"나에게 진실을 말해 줘. = Tell me the truth.",
"그녀는 나에게 문자를 보냈다. = She sent me a text message. | She sent me a text. | She sent a text message to me.",
"그는 우리에게 길을 알려 주었다. = He showed us the way. | He told us the way. | He showed the way to us.",
"나는 남동생에게 장난감을 사 주었다. = I bought my brother a toy. | I bought a toy for my brother.",
"그 웨이터가 우리에게 물을 가져다주었다. = The waiter brought us water. | The waiter brought water to us. | The waiter brought us some water.",
"그녀는 나에게 그녀의 비밀을 말해 주었다. = She told me her secret. | She told her secret to me.",
"우리 팀이 그에게 상을 주었다. = Our team gave him a prize. | Our team gave a prize to him. | Our team gave him an award."
]},
{ id: "c10c", level: "l4", ch: "10장", name: "5형식", short: "5형식",
  tip: "주어 + 동사 + 목적어 + 목적격 보어. call/make + 명사·형용사, want/tell/ask + to부정사, 지각·사역동사 + 동사원형.",
  items: [
"우리는 그를 '왕'이라고 부른다. = We call him King. | We call him the King.",
"그 소식은 나를 행복하게 만들었다. = The news made me happy.",
"그녀는 방을 깨끗하게 유지한다. = She keeps her room clean.",
"그들은 그 아기를 민준이라고 이름 지었다. = They named the baby Minjun.",
"그 영화는 나를 슬프게 만들었다. = The movie made me sad.",
"나는 그 시험이 쉽다는 것을 알게 되었다. = I found the test easy. | I found the exam easy.",
"엄마는 내가 일찍 자기를 원하신다. = Mom wants me to go to bed early. | My mom wants me to go to bed early. | My mother wants me to go to bed early.",
"선생님은 우리에게 조용히 하라고 말씀하셨다. = The teacher told us to be quiet.",
"그는 나에게 그를 도와달라고 부탁했다. = He asked me to help him.",
"의사는 나에게 운동하라고 충고했다. = The doctor advised me to exercise.",
"나의 부모님은 내가 밤에 외출하는 것을 허락하지 않으신다. = My parents don't allow me to go out at night. | My parents do not allow me to go out at night.",
"나는 그가 노래하는 것을 들었다. = I heard him sing. | I heard him singing.",
"나는 그녀가 길을 건너는 것을 보았다. = I saw her cross the street. | I saw her crossing the street. | I saw her cross the road.",
"나는 무언가가 내 다리에 닿는 것을 느꼈다. = I felt something touch my leg. | I felt something touching my leg.",
"엄마는 내가 방을 청소하게 하셨다. = Mom made me clean my room. | My mom made me clean my room. | My mother made me clean my room.",
"아빠는 내가 그의 차를 운전하게 해 주셨다. = Dad let me drive his car. | My dad let me drive his car. | My father let me drive his car.",
"그는 나에게 컴퓨터를 고치게 했다. = He had me fix the computer. | He made me fix the computer.",
"나는 그녀가 숙제하는 것을 도와주었다. = I helped her do her homework. | I helped her to do her homework. | I helped her with her homework.",
"제가 제 소개를 하게 해 주세요. = Let me introduce myself.",
"그녀는 내가 기다리게 했다. = She made me wait. | She kept me waiting."
]},
/* ───────── 고수 · 11장 to부정사와 동명사 ───────── */
{ id: "c11a", level: "l4", ch: "11장", name: "to부정사 명사적 용법", short: "to부정사 명사",
  tip: "to + 동사원형이 '~하는 것'으로 주어·보어·목적어가 돼요. 의문사 + to부정사: how to(~하는 방법), what to(무엇을 ~할지).",
  items: [
"영어를 배우는 것은 재미있다. = To learn English is fun. | It is fun to learn English. | It's fun to learn English.",
"매일 운동하는 것은 중요하다. = It is important to exercise every day. | It's important to exercise every day. | To exercise every day is important.",
"내 꿈은 가수가 되는 것이다. = My dream is to be a singer. | My dream is to become a singer.",
"그의 목표는 시험에 통과하는 것이다. = His goal is to pass the test. | His goal is to pass the exam.",
"나는 파리를 방문하고 싶다. = I want to visit Paris.",
"그녀는 피아노를 배우기로 결심했다. = She decided to learn the piano. | She decided to learn to play the piano.",
"우리는 다음 주에 만나기로 계획했다. = We planned to meet next week.",
"그는 늦지 않겠다고 약속했다. = He promised not to be late.",
"나는 너를 다시 보기를 바란다. = I hope to see you again.",
"그녀는 그 문제를 풀려고 노력했다. = She tried to solve the problem.",
"나는 자전거 타는 방법을 모른다. = I don't know how to ride a bike. | I do not know how to ride a bike. | I don't know how to ride a bicycle.",
"그는 무엇을 말해야 할지 몰랐다. = He didn't know what to say. | He did not know what to say.",
"어디로 가야 할지 나에게 말해 줘. = Tell me where to go.",
"나는 언제 떠나야 할지 결정할 수 없다. = I can't decide when to leave. | I cannot decide when to leave.",
"그녀는 나에게 쿠키 만드는 법을 가르쳐 주었다. = She taught me how to make cookies. | She taught me how to bake cookies.",
"나는 무엇을 사야 할지 모르겠다. = I don't know what to buy. | I do not know what to buy.",
"거짓말하는 것은 나쁘다. = It is bad to lie. | It's bad to lie. | To lie is bad. | Lying is bad.",
"그는 의사가 되고 싶어 한다. = He wants to be a doctor. | He wants to become a doctor.",
"나는 그 책을 읽기 시작했다. = I started to read the book. | I began to read the book. | I started reading the book. | I began reading the book.",
"그녀는 혼자 여행하는 것을 좋아한다. = She likes to travel alone. | She likes traveling alone."
]},
{ id: "c11b", level: "l4", ch: "11장", name: "to부정사 형용사적·부사적 용법", short: "to부정사 형용·부사",
  tip: "명사 뒤에서 '~할'(형용사적), '~하기 위해 / ~해서 / ~하게 되다'(부사적)로 써요.",
  items: [
"나는 마실 것이 필요하다. = I need something to drink.",
"그녀는 할 일이 많다. = She has a lot of work to do. | She has many things to do. | She has a lot of things to do.",
"우리는 쉴 시간이 없다. = We have no time to rest. | We don't have time to rest. | We don't have any time to rest.",
"그는 함께 놀 친구가 없다. = He has no friends to play with. | He doesn't have any friends to play with.",
"나에게 읽을 책을 좀 줘. = Give me a book to read. | Give me some books to read.",
"지금은 잘 시간이다. = It is time to go to bed. | It's time to go to bed. | It is time to sleep. | It's time to sleep.",
"나는 너에게 말할 것이 있다. = I have something to tell you.",
"그녀는 살 집을 찾고 있다. = She is looking for a house to live in.",
"나는 버스를 타기 위해 뛰었다. = I ran to catch the bus.",
"그는 살을 빼기 위해 운동한다. = He exercises to lose weight.",
"우리는 책을 빌리기 위해 도서관에 갔다. = We went to the library to borrow books. | We went to the library to borrow some books.",
"그녀는 의사가 되기 위해 열심히 공부했다. = She studied hard to become a doctor. | She studied hard to be a doctor.",
"나는 그 소식을 들어서 기뻤다. = I was happy to hear the news. | I was glad to hear the news.",
"그는 그녀를 만나서 놀랐다. = He was surprised to meet her. | He was surprised to see her.",
"너를 만나서 반가워. = Nice to meet you. | I'm glad to meet you. | I am glad to meet you. | I'm happy to meet you.",
"그녀는 그 시험에 떨어져서 슬펐다. = She was sad to fail the test. | She was sad to fail the exam.",
"그는 자라서 유명한 화가가 되었다. = He grew up to be a famous painter. | He grew up to become a famous painter.",
"그녀는 아흔 살까지 살았다. = She lived to be ninety. | She lived to be 90.",
"나는 그 사진을 찍기 위해 일찍 일어났다. = I got up early to take the picture. | I woke up early to take the picture. | I got up early to take the photo.",
"우리는 앉을 의자가 필요하다. = We need chairs to sit on. | We need a chair to sit on."
]},
{ id: "c11c", level: "l4", ch: "11장", name: "동명사", short: "동명사",
  tip: "동사-ing가 '~하는 것'으로 주어·보어·목적어가 돼요. enjoy, finish, mind, stop, give up 뒤에는 동명사!",
  items: [
"수영은 좋은 운동이다. = Swimming is good exercise. | Swimming is a good exercise.",
"책을 읽는 것은 재미있다. = Reading books is fun. | Reading books is interesting.",
"일찍 일어나는 것은 쉽지 않다. = Getting up early is not easy. | Getting up early isn't easy. | Waking up early is not easy.",
"내 취미는 사진을 찍는 것이다. = My hobby is taking pictures. | My hobby is taking photos.",
"그의 일은 차를 고치는 것이다. = His job is fixing cars. | His job is repairing cars.",
"나는 음악 듣는 것을 즐긴다. = I enjoy listening to music.",
"그녀는 숙제하는 것을 끝냈다. = She finished doing her homework.",
"그는 담배 피우는 것을 끊었다. = He stopped smoking. | He quit smoking. | He gave up smoking.",
"창문을 열어도 될까요? (꺼리시나요?) = Do you mind opening the window? | Would you mind opening the window?",
"그는 노래하는 것을 잘한다. = He is good at singing.",
"너를 만나기를 고대하고 있어. = I am looking forward to seeing you. | I'm looking forward to seeing you. | I look forward to seeing you.",
"나는 축구하는 것에 관심이 있다. = I am interested in playing soccer. | I'm interested in playing soccer.",
"그녀는 아무 말도 하지 않고 떠났다. = She left without saying anything. | She left without saying a word.",
"늦어서 미안해. = I'm sorry for being late. | I am sorry for being late. | Sorry for being late.",
"나는 수학 공부하는 것을 포기하지 않을 것이다. = I won't give up studying math. | I will not give up studying math.",
"그는 TV 보는 것을 멈추고 잤다. = He stopped watching TV and went to bed. | He stopped watching TV and slept.",
"영화 보러 가는 게 어때? = How about going to the movies? | What about going to the movies? | How about going to see a movie?",
"나는 그 책을 읽기 위해 TV 보는 것을 그만두었다. = I stopped watching TV to read the book.",
"그녀는 요리하는 것을 좋아한다. = She likes cooking. | She likes to cook. | She loves cooking.",
"나는 혼자 있는 것이 싫다. = I don't like being alone. | I do not like being alone. | I hate being alone."
]},
/* ───────── 고수 · 12장 접속사 ───────── */
{ id: "c12a", level: "l4", ch: "12장", name: "and · but · or · so", short: "and·but·or·so",
  tip: "and(그리고), but(그러나), or(또는), so(그래서). both A and B, either A or B도 함께 연습해요.",
  items: [
"나는 사과와 바나나를 좋아한다. = I like apples and bananas.",
"그는 키가 크고 잘생겼다. = He is tall and handsome.",
"그녀는 부자이지만 행복하지 않다. = She is rich, but she is not happy. | She is rich but not happy. | She is rich, but she isn't happy.",
"나는 열심히 공부했지만 시험에 떨어졌다. = I studied hard, but I failed the test. | I studied hard but failed the test. | I studied hard, but I failed the exam.",
"너는 커피를 원하니, 아니면 차를 원하니? = Do you want coffee or tea? | Would you like coffee or tea?",
"우리는 버스나 지하철을 탈 수 있다. = We can take a bus or the subway. | We can take the bus or the subway.",
"나는 피곤해서 일찍 잤다. = I was tired, so I went to bed early. | I was tired, so I slept early.",
"비가 와서 우리는 집에 있었다. = It rained, so we stayed home. | It rained, so we stayed at home. | It was raining, so we stayed home.",
"그녀는 노래하고 춤을 춘다. = She sings and dances.",
"그 방은 작지만 깨끗하다. = The room is small but clean. | The room is small, but it is clean.",
"서둘러라, 그렇지 않으면 늦을 것이다. = Hurry up, or you will be late. | Hurry up, or you'll be late.",
"나는 배가 고파서 라면을 먹었다. = I was hungry, so I ate ramen. | I was hungry, so I had ramen.",
"그는 피아노와 기타 둘 다 칠 수 있다. = He can play both the piano and the guitar.",
"너 아니면 내가 그것을 해야 한다. = Either you or I have to do it. | Either you or I must do it.",
"나는 그에게 전화했지만 그는 받지 않았다. = I called him, but he didn't answer. | I called him, but he did not answer.",
"그녀는 영리하고 친절하다. = She is smart and kind. | She is clever and kind.",
"그 영화는 길었지만 재미있었다. = The movie was long, but it was interesting. | The movie was long but interesting. | The movie was long, but it was fun.",
"감기에 걸려서 나는 학교에 가지 않았다. = I had a cold, so I didn't go to school. | I caught a cold, so I didn't go to school. | I had a cold, so I did not go to school.",
"너는 여기 있어도 되고 가도 된다. = You can stay here or go. | You can stay or go.",
"우리는 저녁을 먹고 영화를 봤다. = We had dinner and watched a movie. | We ate dinner and watched a movie."
]},
{ id: "c12b", level: "l4", ch: "12장", name: "when · while · before · after", short: "시간 접속사",
  tip: "when(~할 때), while(~하는 동안), before(~하기 전에), after(~한 후에). 시간 부사절에서는 미래도 현재형!",
  items: [
"나는 어렸을 때 키가 작았다. = I was short when I was young. | When I was young, I was short. | When I was a child, I was short.",
"그가 왔을 때 나는 자고 있었다. = I was sleeping when he came. | When he came, I was sleeping.",
"집에 도착하면 나에게 전화해. = Call me when you get home. | When you get home, call me. | Call me when you arrive home.",
"나는 슬플 때 음악을 듣는다. = I listen to music when I am sad. | When I'm sad, I listen to music. | When I am sad, I listen to music. | I listen to music when I'm sad.",
"내가 요리하는 동안 그는 설거지를 했다. = He washed the dishes while I was cooking. | While I was cooking, he washed the dishes. | He did the dishes while I was cooking.",
"그녀는 공부하는 동안 음악을 듣는다. = She listens to music while she studies. | While she studies, she listens to music. | She listens to music while studying.",
"엄마가 쇼핑하는 동안 나는 차에서 기다렸다. = I waited in the car while Mom was shopping. | I waited in the car while my mom was shopping. | While my mom was shopping, I waited in the car.",
"자기 전에 이를 닦아라. = Brush your teeth before you go to bed. | Brush your teeth before going to bed. | Before you go to bed, brush your teeth.",
"나는 학교에 가기 전에 아침을 먹는다. = I eat breakfast before I go to school. | I have breakfast before I go to school. | Before I go to school, I eat breakfast.",
"비가 오기 전에 집에 가자. = Let's go home before it rains.",
"나는 숙제를 끝낸 후에 TV를 봤다. = I watched TV after I finished my homework. | After I finished my homework, I watched TV.",
"그는 저녁을 먹은 후에 산책을 했다. = He took a walk after he had dinner. | After he had dinner, he took a walk. | He took a walk after dinner. | He took a walk after he ate dinner.",
"수업이 끝난 후에 만나자. = Let's meet after class. | Let's meet after the class is over. | Let's meet after the class ends.",
"그녀가 떠난 후에 나는 울었다. = I cried after she left. | After she left, I cried.",
"길을 건너기 전에 양쪽을 봐라. = Look both ways before you cross the street. | Look both ways before crossing the street. | Before you cross the street, look both ways.",
"내가 집에 도착했을 때 비가 오고 있었다. = It was raining when I got home. | When I got home, it was raining. | It was raining when I arrived home.",
"그가 내일 오면 나는 그에게 말할 것이다. = When he comes tomorrow, I will tell him. | I will tell him when he comes tomorrow. | I'll tell him when he comes tomorrow.",
"내가 샤워하는 동안 전화가 울렸다. = The phone rang while I was taking a shower. | While I was taking a shower, the phone rang.",
"영화가 시작하기 전에 팝콘을 사자. = Let's buy popcorn before the movie starts. | Let's get popcorn before the movie starts.",
"나는 졸업한 후에 선생님이 될 것이다. = I will be a teacher after I graduate. | After I graduate, I will be a teacher. | I'll become a teacher after I graduate. | I will become a teacher after I graduate."
]},
{ id: "c12c", level: "l4", ch: "12장", name: "because · if · that", short: "because·if·that",
  tip: "because(~ 때문에), if(만약 ~하면, 미래도 현재형), that(~라는 것: think that, know that, hope that).",
  items: [
"나는 아파서 학교에 가지 않았다. = I didn't go to school because I was sick. | Because I was sick, I didn't go to school. | I did not go to school because I was sick.",
"그는 늦게 일어났기 때문에 버스를 놓쳤다. = He missed the bus because he got up late. | Because he got up late, he missed the bus. | He missed the bus because he woke up late.",
"그녀는 친절하기 때문에 인기가 많다. = She is popular because she is kind. | Because she is kind, she is popular.",
"나는 너를 좋아하기 때문에 도와주는 거야. = I help you because I like you. | I'm helping you because I like you.",
"내일 비가 오면 우리는 집에 있을 것이다. = If it rains tomorrow, we will stay home. | We will stay home if it rains tomorrow. | If it rains tomorrow, we'll stay home. | If it rains tomorrow, we will stay at home.",
"열심히 공부하면 너는 시험에 통과할 것이다. = If you study hard, you will pass the test. | You will pass the test if you study hard. | If you study hard, you'll pass the test. | If you study hard, you will pass the exam.",
"배고프면 이 샌드위치를 먹어. = If you are hungry, eat this sandwich. | If you're hungry, eat this sandwich. | Eat this sandwich if you are hungry.",
"시간이 있으면 나에게 전화해. = If you have time, call me. | Call me if you have time.",
"서두르지 않으면 늦을 것이다. = If you don't hurry, you will be late. | If you don't hurry, you'll be late. | You will be late if you don't hurry.",
"그가 오면 나는 기쁠 것이다. = If he comes, I will be happy. | I will be happy if he comes. | I'll be happy if he comes.",
"나는 그가 정직하다고 생각한다. = I think that he is honest. | I think he is honest. | I think he's honest.",
"나는 그녀가 옳다는 것을 안다. = I know that she is right. | I know she is right. | I know she's right.",
"나는 네가 곧 낫기를 바란다. = I hope that you get well soon. | I hope you get well soon. | I hope you get better soon.",
"그는 그것이 사실이라고 말했다. = He said that it was true. | He said it was true.",
"나는 그가 거짓말을 했다고 믿지 않는다. = I don't believe that he lied. | I don't believe he lied. | I do not believe that he lied.",
"문제는 우리가 시간이 없다는 것이다. = The problem is that we don't have time. | The problem is that we have no time. | The problem is that we don't have enough time.",
"나는 그가 이길 것이라고 확신한다. = I am sure that he will win. | I'm sure he will win. | I am sure he will win. | I'm sure that he will win.",
"너는 그녀가 올 거라고 생각하니? = Do you think that she will come? | Do you think she will come? | Do you think she'll come?",
"추워서 나는 창문을 닫았다. = I closed the window because it was cold. | Because it was cold, I closed the window.",
"그녀가 이사 간다는 것은 사실이다. = It is true that she is moving. | It's true that she is moving. | It is true that she is moving away."
]},
/* ───────── 고수 · 13장 전치사 ───────── */
{ id: "c13a", level: "l4", ch: "13장", name: "시간의 전치사", short: "시간 전치사",
  tip: "at(시각), on(요일·날짜), in(월·연도·계절). before/after, for(기간)·during(특정 기간), until(계속)·by(완료).",
  items: [
"수업은 9시에 시작한다. = The class starts at nine. | Class starts at nine. | The class starts at 9. | Class starts at 9.",
"나는 월요일에 그를 만날 것이다. = I will meet him on Monday. | I'll meet him on Monday. | I will see him on Monday.",
"내 생일은 5월에 있다. = My birthday is in May.",
"그는 2012년에 태어났다. = He was born in 2012.",
"우리는 겨울에 스키를 탄다. = We ski in winter. | We go skiing in winter. | We ski in the winter.",
"나는 크리스마스에 선물을 받았다. = I got a present on Christmas. | I got a present on Christmas Day. | I received a present on Christmas.",
"나는 밤에 잠을 잘 못 잔다. = I can't sleep well at night. | I don't sleep well at night.",
"점심 전에 손을 씻어라. = Wash your hands before lunch.",
"방과 후에 축구하자. = Let's play soccer after school.",
"나는 두 시간 동안 공부했다. = I studied for two hours.",
"그녀는 방학 동안 캐나다를 방문했다. = She visited Canada during the vacation. | She visited Canada during vacation.",
"나는 5시까지 너를 기다릴게. = I will wait for you until five. | I'll wait for you until five. | I will wait for you until 5. | I'll wait for you until 5.",
"너는 금요일까지 숙제를 끝내야 한다. = You have to finish your homework by Friday. | You must finish your homework by Friday.",
"그는 6시쯤에 집에 올 것이다. = He will come home around six. | He'll come home around six. | He will come home around 6. | He will come home at around six.",
"영화는 3시간 동안 계속됐다. = The movie lasted for three hours. | The movie lasted three hours.",
"우리는 수업 중에 휴대폰을 사용할 수 없다. = We can't use our phones during class. | We cannot use our phones during class. | We can't use cell phones during class.",
"나는 아침에 우유를 마신다. = I drink milk in the morning.",
"그 가게는 밤 10시까지 연다. = The store is open until ten at night. | The store is open until 10 p.m. | The shop is open until ten at night.",
"그녀는 7월 4일에 떠났다. = She left on July 4th. | She left on July fourth. | She left on July 4.",
"나는 일주일 동안 아팠다. = I was sick for a week. | I was ill for a week."
]},
{ id: "c13b", level: "l4", ch: "13장", name: "장소·위치의 전치사", short: "장소 전치사",
  tip: "in(안), on(위·접촉), at(지점), near, over, under, behind, in front of, next to, across from, between A and B.",
  items: [
"고양이가 상자 안에 있다. = The cat is in the box.",
"책상 위에 공책이 있다. = There is a notebook on the desk.",
"버스 정류장에서 만나자. = Let's meet at the bus stop.",
"그는 서울에 산다. = He lives in Seoul.",
"벽에 시계가 걸려 있다. = There is a clock on the wall.",
"우리 집은 학교 근처에 있다. = My house is near the school. | Our house is near the school.",
"새가 다리 위로 날아갔다. = A bird flew over the bridge. | The bird flew over the bridge.",
"개가 탁자 아래에서 자고 있다. = The dog is sleeping under the table.",
"나무 뒤에 누가 있다. = Someone is behind the tree. | There is someone behind the tree. | Somebody is behind the tree.",
"그는 도서관에 갔다. = He went to the library.",
"차 앞에 소년이 서 있다. = A boy is standing in front of the car. | There is a boy standing in front of the car.",
"그녀는 내 옆에 앉았다. = She sat next to me. | She sat beside me.",
"은행은 우체국 맞은편에 있다. = The bank is across from the post office.",
"그 가게는 은행과 꽃집 사이에 있다. = The store is between the bank and the flower shop. | The shop is between the bank and the flower shop.",
"나는 그 사진을 침대 위에 놓았다. = I put the picture on the bed. | I put the photo on the bed.",
"우리는 공항에 도착했다. = We arrived at the airport.",
"공원에 아이들이 많다. = There are many children in the park. | There are a lot of children in the park. | There are many kids in the park.",
"그의 집은 우리 집 뒤에 있다. = His house is behind my house. | His house is behind ours. | His house is behind our house.",
"남산 위에 탑이 있다. = There is a tower on Namsan. | There is a tower on Namsan Mountain.",
"그녀는 창가 옆에 서 있었다. = She was standing next to the window. | She was standing by the window. | She stood by the window."
]},
{ id: "c13c", level: "l4", ch: "13장", name: "기타 전치사", short: "기타 전치사",
  tip: "for(~을 위해), with(~와 함께, ~로), by(~로, 교통수단), about(~에 대해), from A to B(A에서 B까지).",
  items: [
"이 선물은 너를 위한 것이다. = This present is for you. | This gift is for you.",
"나는 친구들과 함께 영화를 봤다. = I watched a movie with my friends. | I saw a movie with my friends.",
"그는 연필로 그림을 그렸다. = He drew a picture with a pencil.",
"우리는 기차로 부산에 갔다. = We went to Busan by train.",
"그녀는 그녀의 가족에 대해 이야기했다. = She talked about her family.",
"나는 9시부터 5시까지 일한다. = I work from nine to five. | I work from 9 to 5.",
"그는 서울에서 부산까지 운전했다. = He drove from Seoul to Busan.",
"그 책은 동물에 관한 것이다. = The book is about animals.",
"나는 숟가락으로 수프를 먹었다. = I ate the soup with a spoon.",
"그녀는 자전거로 학교에 간다. = She goes to school by bike. | She goes to school by bicycle.",
"엄마를 위해 케이크를 만들자. = Let's make a cake for Mom. | Let's make a cake for our mom. | Let's make a cake for my mom.",
"나는 너에 대해 많이 들었다. = I heard a lot about you. | I have heard a lot about you.",
"그는 긴 머리를 한 소녀를 만났다. = He met a girl with long hair.",
"이 편지는 할머니에게서 온 것이다. = This letter is from my grandmother. | This letter is from my grandma.",
"그 소설은 유명한 작가에 의해 쓰였다. = The novel was written by a famous writer. | The novel was written by a famous author.",
"나는 그 문제에 대해 생각하고 있다. = I am thinking about the problem. | I'm thinking about the problem.",
"그녀는 아침으로 빵을 먹었다. = She had bread for breakfast. | She ate bread for breakfast.",
"우리는 월요일부터 금요일까지 학교에 간다. = We go to school from Monday to Friday.",
"그는 나에게 이메일로 연락했다. = He contacted me by email. | He contacted me by e-mail.",
"나는 그와 함께 숙제를 했다. = I did my homework with him."
]}
];

/* 마스터: 앞 단원을 섞어서 푸는 종합 문제 (문장을 새로 쓰지 않고 위 단원에서 골라요) */
window.MASTER = [
  { id: "m1", name: "종합 1", short: "종합 1", from: ["c2a","c2b","c2c","c3a","c3b","c3c"], tip: "2~3장 be동사·일반동사 총정리" },
  { id: "m2", name: "종합 2", short: "종합 2", from: ["c4a","c4b","c4c","c5a","c5b","c6a","c6b","c6c"], tip: "4~6장 명사·대명사·시제 총정리" },
  { id: "m3", name: "종합 3", short: "종합 3", from: ["c7a","c7b","c7c","c8a","c8b","c8c","c9a","c9b","c9c"], tip: "7~9장 조동사·비교·의문문 총정리" },
  { id: "m4", name: "종합 4", short: "종합 4", from: ["c10a","c10b","c10c","c11a","c11b","c11c"], tip: "10~11장 문장의 형식·to부정사·동명사 총정리" },
  { id: "m5", name: "최종 보스", short: "최종 보스", from: ["c12a","c12b","c12c","c13a","c13b","c13c","c7c","c8c","c10c","c11a","c11b"], tip: "모든 단원에서 어려운 문장만 모았어요" }
];
